services:
    _defaults:
        autowire: false
        autoconfigure: true
        public: false

    BastSys\LocaleBundle\DataFixture\Language\EnglishFixture:
    BastSys\LocaleBundle\DataFixture\Language\CzechFixture:
