services:
    bastsys.language_bundle.event_listener.translation:
        class: BastSys\LocaleBundle\EventListener\TranslationListener
        arguments:
            - '@bastsys.language_bundle.service.locale'
            - '@bastsys.language_bundle.repository.language'
        tags:
            - {name: doctrine.event_subscriber, connection: default}
