services:
    bastsys.locale_bundle.event_listener.country.feed:
        class: BastSys\LocaleBundle\EventListener\Country\CountryFeedListener
        arguments:
            - '@bastsys.locale_bundle.service.country_flag'
        tags:
            - {name: doctrine.event_listener, event: postPersist, entity: BastSys\LocaleBundle\Entity\Country\Country, lazy: true}
            - {name: doctrine.event_listener, event: postLoad, entity: BastSys\LocaleBundle\Entity\Country\Country, lazy: true}
    bastsys.locale_bundle.event_listener.translation:
        class: BastSys\LocaleBundle\EventListener\TranslationListener
        arguments:
            - '@bastsys.locale_bundle.service.locale'
            - '@bastsys.locale_bundle.repository.language'
        tags:
            - {name: doctrine.event_subscriber}
