services:
    _defaults:
        public: true

    bastsys.language_bundle.repository.language:
        class: BastSys\LocaleBundle\Repository\LanguageRepository
        arguments:
            - '@doctrine.orm.entity_manager'
    bastsys.language_bundle.repository.country:
        class: BastSys\LocaleBundle\Repository\CountryRepository
        arguments:
            - '@doctrine.orm.entity_manager'
