services:
    _defaults:
        public: true

    bastsys.locale_bundle.repository.language:
        class: BastSys\LocaleBundle\Repository\LanguageRepository
        lazy: true
        arguments:
            - '@doctrine.orm.entity_manager'
    bastsys.locale_bundle.repository.country:
        class: BastSys\LocaleBundle\Repository\CountryRepository
        arguments:
            - '@doctrine.orm.entity_manager'
    bastsys.locale_bundle.repository.currency:
        class: BastSys\LocaleBundle\Repository\CurrencyRepository
        arguments:
            - '@doctrine.orm.entity_manager'
