services:
    bastsys.language_bundle.service.locale:
        class: BastSys\LocaleBundle\Service\LocaleService
        lazy: true
        arguments:
            - '@bastsys.language_bundle.repository.language'
            - '@bastsys.language_bundle.repository.country'
            - '%bastsys.language_bundle.locale.default%'
