services:
    bastsys.locale_bundle.service.locale:
        class: BastSys\LocaleBundle\Service\LocaleService
        lazy: true
        arguments:
            - '@bastsys.locale_bundle.repository.language'
            - '@bastsys.locale_bundle.repository.country'
            - '%bastsys.locale_bundle.locale.default%'
    bastsys.locale_bundle.service.country_flag:
        class: BastSys\LocaleBundle\Service\CountryFlagService
        arguments:
            - '@assets.packages'
            - '@request_stack'
